---
title: "omni-clustbench across backends+seeds+runs / Fig 2"
author: "Mark Robinson (took a couple snippets from Izaskun's original)"
output:
  html_document:
    theme: readable
    toc: true
    toc_float: true
    code_folding: hide
    code_download: true
    number_sections: true
    df_print: default
    highlight: tango
    keep_md: true
    self_contained: false
date: "`r format(Sys.Date(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
---


```{r setup, message = FALSE}
library(knitr)
library(dplyr)
library(ggplot2)
library(stringr)
library(readr)
library(cowplot)
library(rjson)


knitr::opts_chunk$set(
  echo    = TRUE,
  warning = TRUE,
  message = TRUE,
  fig.width = 10,
  fig.height = 10,
  fig.path = "plots/",
  dev = c("png", "svg"),
  cache.lazy = FALSE,
  cache = TRUE)

```

## Doing updates to local (b/c interactive is easier) via:

```
rsync -avu mark@omnibenchmark.mls.uzh.ch:~/projects/omb/omnibenchmark_paper_code/results/ ./results/
```

```{r}

# Our dirs split look like this:
#[[721]]
# [1] "results"                                   "out-conda_seed-2_run-1"                   
# [3] "data"                                      "clustbench"                               
# [5] "dataset_generator-fcps_dataset_name-tetra" "clustering"                               
# [7] "genieclust"                                "method-ica"                               
# [9] "metrics"                                   "partition_metrics"                        
#[11] "metric-normalized_clustering_accuracy"     "parameters.json"

# "universal" directory name to type
dir_to_type <- function(d) {
  ss <- str_split(dirname(d), fixed("/"))
  bsr <- sapply(ss, .subset, 2) %>%
    str_replace("out_","") %>%
    str_replace("seed_","") %>%
    str_replace("run_","") %>%
    str_split_fixed("-", 3) %>%
    `colnames<-`(c("backend","seed","run"))
    
  dataset <- sapply(ss, .subset, 5) %>% 
    str_replace("dataset_generator-","") %>%
    str_replace("dataset_name-","")

  method <- paste0(sapply(ss, .subset, 7), "_",
                   sapply(ss, .subset, 8))
  method[method=="NA_NA"] <- NA
  
  metric <- sapply(ss, .subset, 11)
  
 data.frame(bsr, dataset, method, metric)
}


extractor <- function(u) {
  if(nrow(u))
      return(data.frame(value=as.numeric(u[1,3]),
                        k=colnames(u)[3]) )
  else
    return( data.frame(value=NA, k=NA) )
}


extractor2 <- function(u) {
  if(nrow(u)) {
    cn <- colnames(u)
    ks <- sapply(strsplit(cn, ".", fixed = TRUE), .subset, 1) %>%
      str_replace("k=","") %>% as.integer
    vs <- as.numeric(u[1,])-as.numeric(u[1,3])
    return(data.frame(v1 = vs[1], v2 = vs[2],
                      v3 = vs[3], v4 = vs[4],
                      v5 = vs[5], true_k=ks[3]) )
  } else
    return( data.frame(v1 = NA, v2 = NA, v3 = NA,
                       v4 = NA, v5 = NA, true_k=NA) )
}




```

## Computational performance

```{r}
# params <- dir(pattern = "parameters.json", 
#               recursive = TRUE)

perf_files <- dir(pattern = "clustbench_performance.txt", 
            recursive = TRUE)
length(perf_files)

# data_files <- dir(pattern = "clustbench.data.gz", 
#             recursive = TRUE)
# data_type <- dir_to_type(data_files)


# only need look at methods-run-on-datasets performance
perf_type <- dir_to_type(perf_files)
head(perf_type, 2)
w <- with(perf_type, !is.na(method) & is.na(metric))
perf_files <- perf_files[w]
perf_type <- perf_type[w,]
length(perf_files)

# read in a ton of 1-line files
system.time({
perfs <- lapply(perf_files, read_tsv, skip = 1, 
         col_names = c("s","time","max_rss","max_vms",
                       "max_uss","max_pss","io_in","io_out",
                       "mean_load","cpu_time"),
         col_types = c("d","t",rep("?",8)),
         n_max = 1) %>% bind_rows()
}) 

perf_df <- cbind(perf_type %>% dplyr::select(-metric), perfs)

# noting high level of NAs in snakemake outputs (many processes are short, I guess)
colMeans(is.na(perf_df))

table(is.na(perf_df$max_rss), is.na(perf_df$io_in))

ggplot(perf_df, aes(x=is.na(cpu_time), y=s)) + geom_violin() + 
  scale_y_log10()

# cpu_time is a lower bound
ggplot(perf_df, aes(x=cpu_time, y=s)) + geom_point() + 
  scale_y_log10() + scale_x_log10() + geom_abline(colour="blue")

perf_df <- perf_df %>% filter(!is.na(cpu_time))

```


## Parsing out clustering performances

```{r}
score_files <- dir(pattern = "clustbench.scores.gz",
                   recursive = TRUE)

score_type <- dir_to_type(score_files)
head(score_type, 2)
nrow(score_type)

system.time({
rawscores <- lapply(score_files, read_csv, 
         col_types = rep("d",5), name_repair = "unique_quiet",
         n_max = 1)
}) 


extracted <- lapply(rawscores, extractor)

table(sapply(extracted, nrow))
nrow(score_type)

scores_df <- data.frame(score_type, extracted %>% bind_rows())

scores_df %>% filter(metric=="metric-adjusted_rand_score",
                     method=="agglomerative_linkage-average",
                     dataset=="fcps_chainlink") %>% 
  dplyr::select(-dataset, -method, -metric)

table(is.na(scores_df$value), scores_df$backend)

scores_df <- scores_df %>% filter(!is.na(value))


# > table(is.na(scores_df$value), scores_df$backend)
#        
#         conda envmodules  oras
#   FALSE 28821      28839 28851
#   TRUE    195        177   162

# extract ARI across values of k
k <- score_type$metric == "metric-adjusted_rand_score" &
  score_type$seed == "20" & score_type$run == "1" & 
  score_type$backend == "conda"

extracted2 <- lapply(rawscores[k], extractor2)

scores_df2 <- data.frame(score_type[k,], 
                         extracted2 %>% bind_rows()) %>%
  select(dataset, method, true_k, v1, v2, v3, v4, v5, true_k)

# boxplot(as.data.frame(scores_df2[,c("v1","v2","v3",
#                                     "v4","v5")]),
#         ylab="delta ARI")

scores_melt <- melt(scores_df2, 
                    id.vars = c("dataset","method","true_k"))

levels(scores_melt$variable) <- c("-2","-1","0","+1","+2")

levels(scores_melt$variable) <- c("-2","-1","0","+1","+2")

scores_melt$module <- factor(sapply(strsplit(scores_melt$method, 
                                    "_", fixed=TRUE), .subset, 1),
                    levels = rev(c("genieclust","sklearn","fastcluster",
                               "agglomerative","fcps")))

scores_melt$method_small <- sapply(strsplit(scores_melt$method, "-", fixed = TRUE), .subset, 2)

p <- ggplot(scores_melt %>% dplyr::filter(!is.na(true_k),
                                     !(true_k==2 & variable %in% c("-2","-1")),
                                     !(true_k==3 & variable %in% c("-2")),
                                     variable != "0"), 
       aes(variable, value)) + 
  geom_boxplot(aes(fill = method, colour = method)) +
  # geom_boxplot(aes(fill = method), colour = "grey50", outlier.shape = NA) +
  # scale_fill_manual(values=my_colors) +
  # scale_colour_manual(values=my_colors) +
  facet_wrap(~dataset, ncol=6) +
  ylim(-.5, .5) + 
  ylab("ARI - ARI(true k)") +
  geom_hline(yintercept = 0, colour="black", linetype="dashed") +
  xlab("Cluster Number Misspecification") +
  theme_classic() +
  theme(legend.position = "top",
        legend.spacing.y = unit(.01, 'cm'),
        legend.key.spacing.y = unit(.01, 'cm'),
        legend.text=element_text(size=6),
        legend.key.height = unit(.1, 'cm'),
        axis.text.x = element_text(size = 12),
        axis.title.x = element_text(size = 14),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        plot.title = element_text(size = 18))

p

ggsave("cluster-misspec-suppfig1.pdf", p, width = 10, height = 12)



```


## Looking at runtime performances

```{r}

dl <- "/"
perf_key <- with(perf_df, paste0(backend, dl, seed, dl, 
                                 run, dl, dataset, dl, method))
score_key <- with(scores_df, paste0(backend, dl, seed, dl, 
                                 run, dl, dataset, dl, method))

length(perf_key)
length(score_key)

# high
mean(perf_key %in% score_key) 

# low; prob b/c many runs are fast and not captured
mean(score_key %in% perf_key) 

# which(!(perf_key %in% score_key))

# only key performances where a score was actually calculated
perf_df <- perf_df %>% filter(perf_key %in% score_key)
dim(perf_df)

cnd <- perf_df %>% filter(backend=="conda") %>% 
  dplyr::select(-backend)
app <- perf_df %>% filter(backend=="oras") %>% 
  dplyr::select(-backend)
lmd <- perf_df %>% filter(backend=="envmodules") %>% 
  dplyr::select(-backend)

df <- inner_join(lmd, app, by = c("seed", "dataset", "method", "run"),
                 suffix = c(".envmodules",".apptainer")) %>%
  inner_join(cnd, by = c("seed", "dataset", "method", "run")) 


df$module <- factor(sapply(strsplit(df$method, 
                                    "_", fixed=TRUE), .subset, 1),
                    levels = rev(c("genieclust","sklearn","fastcluster",
                               "agglomerative","fcps")))
df$seed <- as.factor(df$seed)
df$run <- as.factor(df$run)


my_colors <- c("fcps" = "grey90", "agglomerative" = "salmon",
               "fastcluster" = "lightsteelblue", "sklearn" = "orange",
               "genieclust" = "darkgreen")

common <- list(geom_point(size = 3, alpha = .8),
               scale_x_log10(),
               scale_y_log10(),
               scale_colour_manual(values=my_colors),
               geom_hline(yintercept = 1, colour="black", linetype="dashed"),
               xlab("CPU time(s): conda"),
               theme_classic(),
               theme(legend.spacing.y = unit(.01, 'cm'),
                     legend.key.spacing.y = unit(.01, 'cm'),
                     legend.key.height = unit(.1, 'cm'),
                     axis.text.x = element_text(size = 12),
                     axis.title.x = element_text(size = 14),
                     axis.text.y = element_text(size = 12),
                     axis.title.y = element_text(size = 14),
                     plot.title = element_text(size = 18)))

p_labeling <- list(ylab("CPU time ratio: Apptainer / conda"),
                   ggtitle("omni-clustering-benchmarks:\nApptainer vs. conda"))

q_labeling <- list(ylab("CPU time ratio: EasyBuild / conda"),
                   ggtitle("omni-clustering-benchmarks: \nEasyBuild vs. conda"))



df <- df %>% arrange(module)

(md.app <- median(df$cpu_time.apptainer/df$cpu_time))

k <- df$cpu_time > 1 & (df$cpu_time.apptainer/df$cpu_time < 2) & (df$cpu_time.apptainer/df$cpu_time > .5)



# p <- ggplot(df %>% dplyr::filter(k), 
#        aes(cpu_time, cpu_time.apptainer/cpu_time,
#            shape=seed, colour=module)) +
#   common

(md.app <- median(df$cpu_time.apptainer[k]/df$cpu_time[k]))

p <- ggplot(df %>% dplyr::filter(k), 
       aes(cpu_time, cpu_time.apptainer/cpu_time,
           shape=seed, colour=module)) +
  common +
  p_labeling +
  geom_hline(yintercept = md.app, colour="blue") +
  scale_y_log10(limits = c(.5, 2)) +
  scale_x_log10(limits = c(4,10000)) + 
  theme(legend.position="none")
  
p <- p +
  annotate(geom = "curve", x = 5000, y = 1.414165, xend = 10000, 
           yend = md.app, curvature = -.2, 
           arrow = arrow(length = unit(2, "mm")),
           colour = "blue") +
  annotate(geom = "text", x = 5000, y = 1.6, 
           label = paste0("median relative\nspeed: ", round(md.app, 3)), 
           hjust = "center", colour = "blue")


# take subset
k <- df$cpu_time > 1 & (df$cpu_time.envmodules/df$cpu_time < 2) & (df$cpu_time.envmodules/df$cpu_time > .5)
(md.env <- median(df$cpu_time.envmodules[k]/df$cpu_time[k]))

q <- ggplot(df %>% dplyr::filter(k), 
       aes(cpu_time, cpu_time.envmodules/cpu_time,
           shape=seed, colour=module)) +
  common +
  q_labeling +
  geom_hline(yintercept = md.env, colour="blue") +
  scale_y_log10(limits = c(.5, 2)) +
  scale_x_log10(limits = c(4,10000)) +
  theme(legend.position=c(.85,.22))

q <- q +
  annotate(geom = "curve", x = 5000, y = 1.414165, xend = 10000, 
           yend = md.env, curvature = -.2, 
           arrow = arrow(length = unit(2, "mm")),
           colour = "blue") +
  annotate(geom = "text", x = 5000, y = 1.6, 
           label = paste0("median relative\nspeed: ", round(md.env, 3)), 
           hjust = "center", colour = "blue")

# main figure
ggsave("cpu_time-mainfig.pdf", cowplot::plot_grid(p,q), width = 10, height = 5)



(md.app <- median(df$cpu_time.apptainer/df$cpu_time))

p <- ggplot(df,
       aes(cpu_time, cpu_time.apptainer/cpu_time,
           shape=seed, colour=module)) +
  common +
  p_labeling +
  geom_hline(yintercept = md.app, colour="blue") +
  theme(legend.position = "none")


p <- p +
  annotate(geom = "curve", x = 5000, y = 1.414165, xend = 10000, 
           yend = md.app, curvature = -.2, 
           arrow = arrow(length = unit(2, "mm")),
           colour = "blue") +
  annotate(geom = "text", x = 5000, y = 3, 
           label = paste0("median relative\nspeed: ", round(md.app, 3)), 
           hjust = "center", colour = "blue")


(md.env <- median(df$cpu_time.envmodules/df$cpu_time))

q <- ggplot(df, 
       aes(cpu_time, cpu_time.envmodules/cpu_time,
           shape=seed, colour=module)) +
  common +
  q_labeling +
  geom_hline(yintercept = md.env, colour="blue") +
  theme(legend.position=c(.85,.22))

q <- q +
  annotate(geom = "curve", x = 5000, y = 1.414165, xend = 10000, 
           yend = md.env, curvature = -.2, 
           arrow = arrow(length = unit(2, "mm")),
           colour = "blue") +
  annotate(geom = "text", x = 5000, y = 3, 
           label = paste0("median relative\nspeed: ", round(md.env, 3)), 
           hjust = "center", colour = "blue")




# supp figure
ggsave("cpu_time-suppfig.pdf", cowplot::plot_grid(p,q), width = 10, height = 5)

```


## Looking at memory usage

```{r}

common <- list(geom_point(size = 3, alpha = .8),
               scale_x_log10(),
               scale_y_log10(),
               scale_colour_manual(values=my_colors),
               geom_hline(yintercept = 1, colour="black", linetype="dashed"),
               xlab("Maximum Resident Set Size (MB): conda"),
               theme_classic(),
               theme(legend.spacing.y = unit(.01, 'cm'),
                     legend.key.spacing.y = unit(.01, 'cm'),
                     legend.key.height = unit(.1, 'cm'),
                     axis.text.x = element_text(size = 12),
                     axis.title.x = element_text(size = 14),
                     axis.text.y = element_text(size = 12),
                     axis.title.y = element_text(size = 14),
                     plot.title = element_text(size = 18)))

p_labeling <- list(ylab("Maximum RSS ratio: Apptainer / conda"),
                   ggtitle("omni-clustering-benchmarks:\nApptainer vs. conda"))

q_labeling <- list(ylab("Maximum RSS ratio: EasyBuild / conda"),
                   ggtitle("omni-clustering-benchmarks: \nEasyBuild vs. conda"))

(md.app <- median(df$max_rss.apptainer/df$max_rss))

p <- ggplot(df,
       aes(max_rss, max_rss.apptainer/max_rss,
           shape=seed, colour=module)) +
  common +
  p_labeling +
  geom_hline(yintercept = md.app, colour="blue") +
  theme(legend.position = "none")


p <- p +
  annotate(geom = "curve", x = 5000, y = 2, xend = 10000, 
           yend = md.app, curvature = -.2, 
           arrow = arrow(length = unit(2, "mm")),
           colour = "blue") +
  annotate(geom = "text", x = 5000, y = 3, 
           label = paste0("median relative\nmax. memory: ", round(md.app, 3)), 
           hjust = "center", colour = "blue")


(md.env <- median(df$max_rss.envmodules/df$max_rss))

q <- ggplot(df, 
       aes(max_rss, max_rss.envmodules/max_rss,
           shape=seed, colour=module)) +
  common +
  q_labeling +
  geom_hline(yintercept = md.env, colour="blue") +
  theme(legend.position=c(.8,.3))

q <- q +
  annotate(geom = "curve", x = 5000, y = 2, xend = 10000, 
           yend = md.env, curvature = -.2, 
           arrow = arrow(length = unit(2, "mm")),
           colour = "blue") +
  annotate(geom = "text", x = 5000, y = 3, 
           label = paste0("median relative\nmax. memory: ", round(md.env, 3)), 
           hjust = "center", colour = "blue")


# supp figure
ggsave("max_rss-suppfig.pdf", cowplot::plot_grid(p,q), width = 10, height = 5)


```

## Looking at adjusted rand indices

```{r}

scores_df %>% filter(metric=="metric-adjusted_rand_score",
                     method=="agglomerative_linkage-average",
                     dataset=="fcps_chainlink") %>% 
  dplyr::select(-dataset, -method, -metric)


cnd <- scores_df %>% filter(backend=="conda", 
                            metric=="metric-adjusted_rand_score") %>% 
  dplyr::select(-backend, -metric)
app <- scores_df %>% filter(backend=="oras", 
                            metric=="metric-adjusted_rand_score") %>% 
  dplyr::select(-backend, -metric)
lmd <- scores_df %>% filter(backend=="envmodules", 
                            metric=="metric-adjusted_rand_score") %>% 
  dplyr::select(-backend, -metric)


df <- inner_join(lmd, app, by = c("seed", "dataset", "method", "run"),
                 suffix = c(".envmodules",".apptainer")) %>%
  inner_join(cnd, by = c("seed", "dataset", "method", "run"))

df$module <- sapply(strsplit(df$method, "_", fixed=TRUE), .subset, 1)
df$seed <- as.factor(df$seed)
df$run <- as.factor(df$run)


table(abs(df$value-df$value.apptainer))
table(abs(df$value-df$value.envmodules))

common <- list(geom_point(size = 3, alpha = .8),
               scale_colour_manual(values=my_colors),
               xlab("Adjusted Rand Index: conda"),
               geom_point(size = 3, alpha = .8),
               geom_abline(colour="black", linetype="dashed"),
               theme_classic(),
               theme(legend.spacing.y = unit(.01, 'cm'),
                     legend.key.spacing.y = unit(.01, 'cm'),
                     legend.key.height = unit(.1, 'cm'),
                     axis.text.x = element_text(size = 12),
                     axis.title.x = element_text(size = 14),
                     axis.text.y = element_text(size = 12),
                     axis.title.y = element_text(size = 14),
                     plot.title = element_text(size = 18),
                     legend.text=element_text(size=8)))


p <- ggplot(df, aes(value, value.apptainer,
                    shape=seed, colour=module)) + 
  common +
  ylab("Adjusted Rand Index: Apptainer") +
  theme(legend.position=c(.25,.75)) +
  ggtitle("omni-clustering-benchmarks:\nApptainer vs. conda")

q <- ggplot(df, aes(value, value.envmodules,
                    shape=seed, colour=module)) + 
  common +
  ylab("Adjusted Rand Index: EasyBuild") +
  theme(legend.position="none") +
  ggtitle("omni-clustering-benchmarks:\nEasyBuild vs. conda")

q <- q +
  annotate(geom = "curve", x = .65, y = .3, xend = .29, 
           yend = .1443, curvature = -.2, 
           arrow = arrow(length = unit(2, "mm")),
           colour = "blue") +
  annotate(geom = "text", x = .65, y = .34, label = "Ward (wut/z1)", 
           hjust = "center", colour = "blue")

ggsave("aris-mainfig.pdf", cowplot::plot_grid(p,q), width = 10, height = 5)

  
# ggplot(df, aes(value, value.envmodules)) + 
#   geom_point()

df %>% dplyr::filter(abs(value-value.envmodules)>0.001 |
                       abs(value-value.apptainer)>0.001) %>%
  dplyr::select(-k.apptainer,-k.envmodules)
df %>% dplyr::filter(abs(value-value.envmodules)>0.1 |
                       abs(value-value.apptainer)>0.1) %>%
  dplyr::select(-k.apptainer,-k.envmodules)


# there is one case where they are different
df <- inner_join(lmd %>% dplyr::filter(run == "1"), 
                 app %>% dplyr::filter(run == "1"), 
                 by = c("dataset", "method", "run"),
                 suffix = c(".envmodules",".apptainer"),
                 relationship = "many-to-many") %>%
  inner_join(cnd %>% dplyr::filter(run == "1"), 
             by = c("dataset", "method", "run"),
             relationship = "many-to-many") %>%
  dplyr::select(-run, -k.apptainer, -k.envmodules) %>%
  dplyr::filter(seed.envmodules != seed,
                seed.apptainer != seed)

df %>% filter(abs(value-value.envmodules)>0.0000001)


```


## Aidan's running of Open Problems - figures

```{r}

ddir <- "sharing"
list.files(ddir)

ob <- read_csv(file.path(ddir, "aggregated_scores.csv"))

rl <- readLines(file.path(ddir, "op_svg_results.json"))
js <- fromJSON(paste(rl, collapse = ""))
# op <- lapply(js, function(u) data.frame(dataset_id = u$dataset_id,
#                                         method_id = u$method_id,))

op <- data.frame(dataset_id = sapply(js, .subset2, "dataset_id"),
                 method_id = sapply(js, .subset2, "method_id"),
                 metric_id = "correlation",
                 op_metric_value = sapply(js, function(u) u$metric_values$correlation),
                 op_mean_score = sapply(js, .subset2, "mean_score"))

lookup <- rbind( c('tenx_visium/visium', 'spatial_10x_visium'),
                 c('tenx_visium/post_xenium', 'spatial_10x_xenium'),
                 c('zenodo_spatial/dbitseq', 'spatial_dbit_seq'),
                 c('zenodo_spatial/merfish', 'spatial_merfish'),
                 c('zenodo_spatial/seqfish', 'spatial_seqfish'),
                 c('zenodo_spatial/slideseqv2', 'spatial_slideseq_v2'),
                 c('zenodo_spatial_slidetags/slidetags', 'spatial_slide_tags'),
                 c('zenodo_spatial/starmap', 'spatial_star_map'),
                 c('zenodo_spatial/stereoseq', 'spatial_stereo_seq'),
                 c('zenodo_spatial/visium', 'spatial_10x_visium'),
                 c("tenx_visium/visium/mouse_brain_coronal",
                   "tenx_visium/visium/mouse_brain_coronal_section1"),
                 # c("zenodo_spatial/seqfish/mouse_organogenesis_seqfish",
                 #   "zenodo_spatial/seqfish/mouse_organogenesis"),
                 c("zenodo_spatial/visium/human_heart_myocardial_infarction_1",
                   "tenx_visium/visium/human_heart_myocardial_infarction_1"),
                 c("zenodo_spatial/visium/human_heart_myocardial_infarction_2",
                   "tenx_visium/visium/human_heart_myocardial_infarction_2"))


ob[grep("human_colon_cancer", ob$dataset_id),]
op[grep("human_colon_cancer", op$dataset_id),]

for(i in 1:nrow(lookup)) {
  ob$dataset_id <- gsub(lookup[i,2], lookup[i,1], ob$dataset_id)
}

sum(ob$dataset_id %in% op$dataset_id)

setdiff(ob$dataset_id, op$dataset_id)
setdiff(op$dataset_id, ob$dataset_id)

m <- full_join(ob, op)
m$op_metric_value <- as.numeric(m$op_metric_value)

m %>% group_by(method_id) %>% 
  summarise(diff=mean(abs(metric_value-op_metric_value), na.rm=TRUE),
            op_nonNA = mean(!is.na(metric_value))) %>%
  arrange(desc(diff))

ggplot(na.omit(m) %>% filter(method_id != "true_ranking"), 
       aes(metric_value, op_metric_value)) + 
  geom_point(size=2) + 
  geom_abline(colour="blue") +
  facet_wrap(~method_id, scales = "free") +
  xlab("ob") + ylab("op")


m$method <- "other"
m$method[m$method_id=="spagcn"] <- "SpaGCN"
m$method[m$method_id=="spatialde2"] <- "spatialde2"


ggplot(na.omit(m) %>% filter(method_id != "true_ranking") %>% arrange(desc(method)), 
       aes(metric_value, op_metric_value, colour=method)) + 
  geom_point(size=3, alpha = .8) + 
  scale_colour_manual(values=c("grey","blue","orange")) +
  geom_abline(colour="black", linetype="dashed") +
  xlab("Kendalls tau: Omnibenchmark") + ylab("Kendall's tau: OpenProblems") +
  theme_classic() +
  theme(legend.position=c(.25,.75), 
        legend.spacing.y = unit(.01, 'cm'),
        legend.key.spacing.y = unit(.01, 'cm'),
        legend.key.height = unit(.4, 'cm'),
        axis.text.x = element_text(size = 12),
        axis.title.x = element_text(size = 14),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        plot.title = element_text(size = 18),
        legend.text=element_text(size=12)) +
  ggtitle("omni-OpenProblems-svg")


ggsave("ob-op.pdf", width = 5, height = 5)


m %>% group_by(method_id) %>%
  summarise(diff=mean(abs(metric_value-op_metric_value), na.rm=TRUE),
            op_nonNA = mean(!is.na(metric_value))) %>%
  arrange(desc(diff))

# ggplot(na.omit(m) %>% 
#          filter(method_id != "true_ranking") %>% arrange(method),
#        aes(metric_value, op_metric_value)) +
#   geom_point(size=2) +
#   geom_abline(colour="blue") +
#   facet_wrap(~method_id, scales = "free") +
#   theme_classic() +
#   xlab("ob") + ylab("op")
```


